Fix 500 error when requesting sitemap.xml
The production build would get this error since the `markdown/`
directory would not be available there:
```
Error: ENOENT: no such file or directory, scandir 'markdown/en/blogs'
    at readdirSync (node:fs:1039:3)
    at getServerSideProps (/home/user/app/.next/server/pages/sitemap.xml.js:457:81)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async renderToHTML (/home/user/app/node_modules/next/dist/next-server/server/render.js:40:215)
    at async /home/user/app/node_modules/next/dist/next-server/server/next-server.js:107:97
    at async /home/user/app/node_modules/next/dist/next-server/server/next-server.js:100:142
    at async Server.renderToHTMLWithComponents (/home/user/app/node_modules/next/dist/next-server/server/next-server.js:132:387)
    at async Server.renderToHTML (/home/user/app/node_modules/next/dist/next-server/server/next-server.js:133:522)
    at async Server.render (/home/user/app/node_modules/next/dist/next-server/server/next-server.js:72:236)
    at async Object.fn (/home/user/app/node_modules/next/dist/next-server/server/next-server.js:56:580)
    at async Router.execute (/home/user/app/node_modules/next/dist/next-server/server/router.js:23:67)
    at async Server.run (/home/user/app/node_modules/next/dist/next-server/server/next-server.js:66:1042)
    at async Server.handleRequest (/home/user/app/node_modules/next/dist/next-server/server/next-server.js:34:1081) {
  errno: -2,
  syscall: 'scandir',
  path: 'markdown/en/blogs'
}
```